version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: password
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  app1:
#    build: .
#    ports:
#      - "8083:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
#    depends_on:
#      - db
#
#  app2:
#    build: .
#    ports:
#      - "8082:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
#    depends_on:
#      - db
#
#  app3:
#    build: .
#    ports:
#      - "8081:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
#    depends_on:
#      - db

volumes:
  postgres_data:
