server:
  tomcat:
    connection-timeout: 100
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
org.jobrunr:
  dashboard:
    enabled: true
    port: 8000
  background-job-server:
    enabled: true
    poll-interval-in-seconds: 5
    worker-count: 5