server:
  tomcat:
    connection-timeout: 2000
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml